# Generated by Django 3.0.5 on 2020-05-02 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='post_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bot.Channel'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='notification_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to='bot.Channel'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='bot.Comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bot.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bot.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buttonemoji',
            name='button_emoji_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_emojis', to='bot.Channel'),
        ),
        migrations.AddField(
            model_name='buttonclick',
            name='click_button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='bot.Button'),
        ),
        migrations.AddField(
            model_name='buttonclick',
            name='click_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='bot.Channel'),
        ),
        migrations.AddField(
            model_name='buttonclick',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='button',
            name='button_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='bot.Channel'),
        ),
        migrations.AddField(
            model_name='button',
            name='button_emoji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='bot.ButtonEmoji'),
        ),
        migrations.AddField(
            model_name='button',
            name='button_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='bot.Post'),
        ),
    ]
